dist: trusty
sudo: required
language: c++

cache:
  directories:
    - $HOME/.cache/bazel
  timeout: 500
before_cache:
  - sudo rm -rf $HOME/.cache/bazel/_bazel_travis/install

os:
  - linux

env:
  - V=0.4.3

before_install:
  - OS=linux
  - ARCH=x86_64
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  - sudo mkdir -p $HOME/.cache/bazel
  - sudo chown -R travis:travis $HOME/.cache/bazel
  - sudo chmod -R 777 $HOME/.cache/bazel
  - sudo rm -rf $HOME/.cache/bazel/_bazel_travis/install
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y g++-5 gcc-5 python-numpy python3-numpy python3-scipy python3-matplotlib bazel
  - g++ --version

script:
  - |
    bazel \
      build \
      --verbose_failures \
      --test_output=errors \
      --local_resources=400,2,1.0 \
      --worker_verbose \
      //...
  - |
    bazel \
      test \
      //...
notifications:
  email: false
